# Generated by Django 5.1.4 on 2025-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Witcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('school', models.CharField(choices=[('wolf', 'Школа Волка'), ('cat', 'Школа Кота'), ('bear', 'Школа Медведя'), ('griffin', 'Школа Грифона'), ('viper', 'Школа Гадюки')], max_length=20, verbose_name='Школа')),
                ('signs', models.JSONField(default=list, verbose_name='Знаки')),
                ('toxicity', models.IntegerField(default=0, verbose_name='Токсичность')),
                ('vitality', models.IntegerField(default=100, verbose_name='Жизненная сила')),
                ('stamina', models.IntegerField(default=100, verbose_name='Выносливость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ведьмак',
                'verbose_name_plural': 'Ведьмаки',
            },
        ),
    ]
