# Generated by Django 5.1.4 on 2025-05-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('potion', 'Зелье'), ('bomb', 'Бомба'), ('oil', 'Масло'), ('decoction', 'Отвар')], max_length=20, verbose_name='Тип')),
                ('toxicity', models.IntegerField(default=0, verbose_name='Токсичность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.JSONField(default=list, verbose_name='Ингредиенты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Алхимический предмет',
                'verbose_name_plural': 'Алхимические предметы',
            },
        ),
    ]
