# Generated by Django 5.1.4 on 2025-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0003_schooluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('necrophage', 'Некрофаг'), ('specter', 'Призрак'), ('vampire', 'Вампир'), ('elemental', 'Элементаль'), ('hybrid', 'Гибрид'), ('draconid', 'Драконид'), ('insectoid', 'Насекомое'), ('cursed', 'Проклятый'), ('relict', 'Реликт')], max_length=20, verbose_name='Тип')),
                ('weaknesses', models.JSONField(default=list, verbose_name='Слабости')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Монстр',
                'verbose_name_plural': 'Монстры',
            },
        ),
    ]
