# Generated by Django 5.1.4 on 2025-05-17 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witcher', '0004_monster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='rank',
            field=models.CharField(choices=[('novice', 'Новичок'), ('master', 'Мастер')], default='novice', max_length=20, verbose_name='Ранг'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(verbose_name='Вознаграждение')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Выполнен'), ('failed', 'Провален')], default='active', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witcher.monster', verbose_name='Монстр')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
